### PR TITLE
Fix #79: BSF scoring is wrong with case-varying names

### LINKED ISSUE #79: Incorrect scoring of BSF
```javascript
    it('should handle tests that arent in all (three) browsers', () => {
      const expectedBrowsers = new Set(['chrome', 'firefox', 'safari']);

      let chromeTree = new TreeBuilder()
          .addTest('TestA', 'OK')
          .addSubtest('TestA', 'Test (upper)', 'PASS')
          .build();

      let firefoxTree = new TreeBuilder()
          .addTest('TestA', 'OK')
          .addSubtest('TestA', 'test (lower)', 'PASS')
          .build();

      let safariTree = new TreeBuilder()
          .addTest('TestA', 'OK')
          .addSubtest('TestA', 'Test (upper)', 'PASS')
          .addSubtest('TestA', 'test (lower)', 'PASS')
          .build();
      
      let runs = [
          { browser_name: 'chrome', tree: chromeTree },
          { browser_name: 'firefox', tree: firefoxTree },
          { browser_name: 'safari', tree: safariTree },
      ];

      let scores = browserSpecific.scoreBrowserSpecificFailures(runs, expectedBrowsers);
      assert.deepEqual(scores, new Map([['chrome', 0.5], ['firefox', 0.5], ['safari', 0.0]]));
    });
```

This currently fails with a result of:

```javascript
      assert.deepEqual(scores, new Map([['chrome', 0.3333333333333333], ['firefox', 0], ['safari', 0]]));
```

This also isn't hypothetical: this affects the scoring of [clear-site-data/storage.https.html](https://wpt.fyi/results/clear-site-data/storage.https.html?sha=fdb441a036fae9246b9f7348778a41e2d233f5c5&label=master&label=experimental&product=chrome&product=firefox&product=safari) among many other tests.

### PR DESCRIPTION
**Pull request by gsnedders**
The important thing to remember is that we need to use the same comparator everywhere; it matters much less what it is than that it is consistent.

Fixes #79.

I don't know quite what we want to do here, given this is in principle a breaking change. It's also potentially not the only one I might find in the near future, so maybe we should hold off a little?

### CODE REVIEW

File: test/browser-specific.js [hunk 1]
```diff
@@ -388,6 +388,35 @@ describe('browser-specific.js', () => {
       let scores = browserSpecific.scoreBrowserSpecificFailures(runs, expectedBrowsers);
       assert.deepEqual(scores, new Map([['chrome', 0], ['firefox', 0]]));
     });
+
+    it('should handle tests that arent in all (three) browsers', () => {
+      const expectedBrowsers = new Set(['chrome', 'firefox', 'safari']);
+
+      let chromeTree = new TreeBuilder()
+          .addTest('TestA', 'OK')
+          .addSubtest('TestA', 'Test (upper)', 'PASS')
```
Comment (foolip) [inline test/browser-specific.js:397]: Is there any significance to the "upper" and "lower" bits in these test names? The test names aren't the same ignoring casing, so it's just the same as calling the tests "Subtest 1" and "Subtest 2"? If so, that would be clearer.

**Review by foolip — COMMENTED** [review]
Have you checked what effect this will have on the metric?

Reading https://github.com/Ecosystem-Infra/wpt-results-analysis/issues/79 I actually can't figure out if there's a problem with case sensitivity, and the changes don't seem to do anything about case sensitivity. `'a'.localeCompare('A')` isn't 0, it seems like the root issue is really that there are two ways of comparing strings.

**Comment by gsnedders** [comment]
> Have you checked what effect this will have on the metric?

 sha                | date       | chrome-version   | chrome            | firefox-version | firefox            | safari-version | safari             
--------------------|------------|------------------|-------------------|-----------------|--------------------|----------------|--------------------
 main               | 2022-02-10 | 100.0.4867.0 dev | 658.7207423306902 | 99.0a1          | 1550.9580147634633 | 139 preview    | 4525.8265184805705 
 bsf-sorting-fix    | 2022-02-10 | 100.0.4867.0 dev | 658.3373640180002 | 99.0a1          | 1552.001833927614  | 139 preview    | 4526.724262921942

**Comment by gsnedders** [comment]
> Reading #79 I actually can't figure out if there's a problem with case sensitivity, and the changes don't seem to do anything about case sensitivity. `'a'.localeCompare('A')` isn't 0, it seems like the root issue is really that there are two ways of comparing strings.

Right, it's not per-se about case sensitivity, it's just that this is (AFAIK) the only place where the localeless `localeCompare` differs is case.

Notably, the problem is:

```
> 'a'.localeCompare('A')
< -1
> ('a' > 'A') - ('a' < 'A')
< 1
```

We might actually want to make the bigger change to make the comparator the latter, which gives us a stable ordering but without having to worry about locales. It does, of course, change the existing order, so might change further insignificant bits of the results (due to float addition not being associative).

File: test/browser-specific.js (hunk 1 above)
Comment (gsnedders) [reply test/browser-specific.js:397]: See comment below. We need somewhere where `'a'.localeCompare('A')` and `('a' > 'A') - ('a' < 'A')` differ, which just so happens to basically only be case.

**Comment by gsnedders** [comment]
Looking at this again, I think I'd rather just change the comparator to the simplistic `(a > b) - (a <  b)`, which avoids `localeCompare` which is… never a great function to be using.

**Comment by foolip** [comment]
@gsnedders if you'd like to get rid of `localeCompare` and use the same comparator consistently, that sounds great. Updating the PR title and description a bit would be nice too, but not super important.

**Comment by foolip** [comment]
> > Updating the PR title and description a bit would be nice too, but not super important.
> 
> I still don't see what's wrong with them? Like, AFAIK, the case difference is the only case this occurs.

Then I don't understand https://github.com/Ecosystem-Infra/wpt-results-analysis/pull/80#discussion_r804433663. Why isn't the test exercising a case difference if this is the only case where the problem occurs?

File: test/browser-specific.js (hunk 1 above)
Comment (gsnedders) [reply test/browser-specific.js:397]: per discussion with @foolip earlier, gonna change these to `TEST (upper)` and `test (lower)`

**Review by foolip — APPROVED** [review]

**Comment by foolip** [comment]
Thanks @gsnedders!
